### ISSUE TITLE
Not receiving the item

### ISSUE THREAD

**Issue by GregClub5** [ServerSelectorX/ServerSelectorX#102]
Hi, new players are not receiving the item to access the gui and /menu doesn't work could you give me a hand on whats wrong please the config is default 

[EDIT Derkades: Removed config, please use https://hastebin.com]

**Comment by Derkades** [comment]
Can you join the server then check your console for errors?

**Comment by GregClub5** [comment]
Sure thing thanks just found this 

ERROR Cannot load plugins/ServerSelectorX/menu/default.yml

**Comment by Derkades** [comment]
Please send the full error, not just the first line

**Comment by GregClub5** [comment]
07.09 15:33:44 [Server] ERROR Cannot load plugins/ServerSelectorX/menu/default.yml
07.09 15:33:44 [Server] INFO org.bukkit.configuration.InvalidConfigurationException: while scanning an anchor
07.09 15:33:44 [Server] INFO in 'string', line 93, column 10:
07.09 15:33:44 [Server] INFO - &3Skyblock!
07.09 15:33:44 [Server] INFO ^
07.09 15:33:44 [Server] INFO expected alphabetic or numeric character, but found !(33)
07.09 15:33:44 [Server] INFO in 'string', line 93, column 20:
07.09 15:33:44 [Server] INFO - &3Skyblock!
07.09 15:33:44 [Server] INFO ^

**Comment by Derkades** [comment]
Enclose strings in quotation marks.

Your config:
```
- &3Skyblock!
```
The proper way:
```
- '&3Skyblock!'
```

**Comment by GregClub5** [comment]
-facepalm- how didn't i see that sorry for wasting your time. there is just one other issue i do not know if it is obvious or not but book doesn't open any ideas please
https://pastebin.com/ZSTZa2Tt

**Comment by Derkades** [comment]
Are you using the correct item name?
Bukkit Material List 1.13.1
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
Bukkit Material List 1.8
http://docs.codelanx.com/Bukkit/1.8/org/bukkit/Material.html

**Comment by Derkades** [comment]
probably a different error then, can you post your default.yml file to https://hastebin.com

**Comment by GregClub5** [comment]
Sure thing thanks 

https://pastebin.com/F9bfhffU

**Comment by GregClub5** [comment]
Sorry i thought you put paste bin i never used it before i belive this should work if not 
https://hastebin.com/about.md

**Comment by Derkades** [comment]
If you are on <1.13 change DARK_OAK_DOOR -> DARK_OAK_DOOR_ITEM

**Comment by GregClub5** [comment]
We are currently running 1.8 spigot and I tried that any way and a different block and still couldn't open the GUI

**Comment by Derkades** [comment]
If you're still having this issue, please send your config.yml and the console error again.
