### ISSUE TITLE
Items not working

### ISSUE THREAD

**Issue by DoreK333** [ServerSelectorX/ServerSelectorX#105]
I can not use some item.
It does not work, for example LIGHT_BLUE_CONCRETE or OAK_PLANKS.
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html

Error: https://hastebin.com/upowixukur.cs

**Comment by ItzJustPammie** [comment]
Which server version are you using?

**Comment by DoreK333** [comment]
1.13.1

**Comment by Derkades** [comment]
Don't use item names that start with `LEGACY_`.

**Comment by DoreK333** [comment]
I do not use such items.

**Comment by Derkades** [comment]
I think you do, the error says this
```No enum constant org.bukkit.Material.LEGACY_LIGHT_BLUE_CONCRETE```

Can you send your menu file? (if multiple, send all)
