### ISSUE TITLE
Support for head database heads

### ISSUE THREAD

**Issue by Derkades** [ServerSelectorX/ServerSelectorX#113]
See api section here: https://www.spigotmc.org/resources/head-database.14280/

**Comment by norfair00** [comment]
Feature is added ?

**Comment by Derkades** [comment]
Thanks for the reminder, I've added it to the plugin. Expect it next update!

**Comment by norfair00** [comment]
Nice thanks nice plugins

**Comment by Derkades** [comment]
Unfortunately I had to remove it because Head Database apparently does not have an open source api or a public maven repository. I'll have to wait for the developer to add that before I can compile the plugin

**Comment by TimRambo** [comment]
There is an api jar on their page but ill just paste it here
https://timrambo.eu/i/y8e.png
https://mega.nz/#!aoUCVI6C!REDes99H-UUtpG5Ot-eKXzHZ8HtHF8uKaaiBK7VvOgg

**Comment by Derkades** [comment]
you can now use `hdb:<id>` for items
