### ISSUE TITLE
could not pass PlayerInteractEvent to ServerSelectorX vPremium-1.4.4

### ISSUE THREAD

**Issue by BomBardyGamer** [ServerSelectorX/ServerSelectorX#118]
Hello,
I have recently purchased ServerSelectorX Premium because I wanted to have a menu with -1 being blank spaces and I know that does not work on ServerSelectorX free. However, I still cannot understand this issue that I get. The compass menu in my inventory will not open no matter what.
I am using the following setup:
Paper 1.12.2
ServerSelectorX Premium 1.4.4

Here is my console log of the error:
https://pastebin.com/E5T5GsKG

Also, here is my configuration file:
https://ufile.io/qvi3q

Please help me understand what I am doing wrong here.

**Comment by Derkades** [comment]
You are using the item name IRON_BARS, which is incorrect. Please use IRON_FENCE instead. See http://docs.codelanx.com/Bukkit/1.8/org/bukkit/Material.html for a list of item names.

Side note: the -1 option is not a premium-only feature
