### ISSUE TITLE
Suggestion: Parse nested placeholders

### ISSUE THREAD

**Issue by sachk** [ServerSelectorX/ServerSelectorX#124]
Hey, I'm trying to use this plugin to display the players rank on the hungergames leaderboard. I wrote a connector for this, and everything works except for parsing the placeholder.

Here's the placeholder I am trying to use

`{hg-player-{player}}`

This just returns `{hg-player-SachK}` (for my username), however putting `{hg-player-sachk}` in the configuration returns the actual value of the placeholder (one in this case). Alternatively, is there a different way to do this - I need to display a placeholder from another server based on the name of the player.

**Comment by Derkades** [comment]
I have thought about implementing player-specific placeholders in SSX-Connector, but I couldn't figure out how to do that without sending massive amounts of data or it being slow.

I think the best solution is to make the hub provide a list of online players which the connector queries and uses to determine which placeholders to upload. I'll work on implementing this for the next SSX-Connector version

**Comment by sachk** [comment]
Nice, I saw you added this in the latest commit. Currently, how would you use this, or is it not complete yet?

**Comment by Derkades** [comment]
I haven't added it, the latest commit is unrelated

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Derkades** [comment]
Will be possible in 2.0.0
