### ISSUE TITLE
permissions-enabled exists but is not added to the config by default. 

### ISSUE THREAD

**Issue by krusic22** [ServerSelectorX/ServerSelectorX#126]
Since the option provides "ssx.join.", I do understand why.
But regardless it should be exposed in the config, so that normal users can find it and disable the compass for certain groups.

**Comment by Derkades** [comment]
The option is present in the default config, but it is commented out

**Comment by krusic22** [comment]
I don't see it in the free version. Might be in the premium version.

**Comment by Derkades** [comment]
The free version does not have permissions. Make sure to skip wiki articles for the premium version

**Comment by krusic22** [comment]
The check still exists in the free version. So I don't see a reason not to include at least the basics. 
OnJoinListener.java:30-34.

**Comment by Derkades** [comment]
Oh, then I must've forgotten about it. Does it work? If so, I will add it to the config

**Comment by krusic22** [comment]
This part does nothing currently `config.getName().replace(".yml", "")`
So the permission is just ssx.join.
The only thing it does it prevents the user from getting a compass. If the user already has a compass they can still use it.
Useful in my case as Paper allows you to not save player data.
