### ISSUE TITLE
Could not pass event PlayerInteractEvent to ServerSelectorX v3.4.0 (MC Ver: 1.14.4)

### ISSUE THREAD

**Issue by ktg5** [ServerSelectorX/ServerSelectorX#134]
When using the plugin with my "custom" config, I simply get an error saying this:

https://pastebin.com/5DsJ0Zm9

Config file download:
https://drive.google.com/file/d/19D1rcYp2cDaBY_fk36YfCFxAjXr4dFSK/view?usp=sharing

It just might be me being stupid once again.

**Comment by Derkades** [comment]
This is because of a configuration file syntax error. There should be an error when the plugin loads telling you what the syntax error is. Alternatively, you can check your config with http://www.yamllint.com/ .

In this case it was a quotes issue, change the lore to this:
```yaml
item-lore: 
 - "Join other servers, without commands."
 - "NOTE, when wanting to join another server, you will have to reconnect to this world (named lobby) and reconnect like that if you don't want to use commands"
```
