### ISSUE TITLE
Plugin tries to connect to the server ignoring config (premium)

### ISSUE THREAD

**Issue by Kalendarz2** [ServerSelectorX/ServerSelectorX#136]
**Minecraft version: 1.14
Plugin version: 2.0.0-rc4**

SSX triest to connect to the bungeecord server, even if the player doesn't have the permission (permission: 'ssx.permission'). 
When _offline-cancel-connect_ is set to true, plugin still shows default disconnect message.
Custom menu open sounds don't work either.

**Comment by Derkades** [comment]
> SSX triest to connect to the bungeecord server, even if the player doesn't have the permission (permission: 'ssx.permission').
Issues with the permissions are fixed in the next version

> When offline-cancel-connect is set to true, plugin still shows default disconnect message.
I've created new issue: #137 

> Custom menu open sounds don't work either.
Make sure that you are using the correct sound names for your version.
