### ISSUE TITLE
[premium] somethimes menu don`t work an player can take items out.

### ISSUE THREAD

**Issue by baxandrei** [ServerSelectorX/ServerSelectorX#139]
ServerSelectorX-Premium-2.0.0-rc4-legacy.jar
 This server is running Paper version git-Paper-647 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

https://youtu.be/ED6kup0ceJ8

**Comment by Derkades** [comment]
Make sure that you do not have multiple menus with the same title. If you don't, it can be caused by incompatibility with another plugin or a laggy server. I've fixed these issues in the next version, so it will always work.

**Comment by baxandrei** [comment]
I have only one menu and server have lowest ping. I will wait for next update, thanx.

**Comment by Derkades** [comment]
A beta version where this is hopefully fixed is available through the discord server
