### ISSUE TITLE
Doesn't work on a modded server running 1.12.2

### ISSUE THREAD

**Issue by johncsuti** [ServerSelectorX/ServerSelectorX#140]
Your remote ping doesn't get info on forge servers and will always show the server as offline, no matter what i try to do. It would be helpful if this would work as my network is a modded and vanilla server network.
![Screenshot_2019-10-01 https api minetools eu](https://user-images.githubusercontent.com/22971404/66014084-81304980-e49b-11e9-88c2-7a23b2051919.png)

**Comment by Derkades** [comment]
The server type doesn't really matter for pinging, it should ping vanilla, spigot, sponge, forge, any server just fine. Can you share the URL that returns this error?

**Comment by johncsuti** [comment]
https://api.minetools.eu/ping/play.64stacks.com/25567

**Comment by johncsuti** [comment]
Thanks I didn’t know it was a separate thing I just saw the link in your wiki and thought it was yours

**Comment by Derkades** [comment]
I didn't know that apparently forge has a different pinging system. Hopefully the author of api.minetools.eu can add support

**Comment by Derkades** [comment]
The issue has been fixed by the API maintainer

**Comment by norfair00** [comment]
Latest version sponge connector not work on 1.12.2 forge server!

**Comment by Derkades** [comment]
@norfair00 this is an unrelated issue, can you open a new issue and provide more information? What is not working? Errors?
