### ISSUE TITLE
Menu does not work properly when activated by clicking on a block (Premium)

### ISSUE THREAD

**Issue by Kalendarz2** [ServerSelectorX/ServerSelectorX#143]
- Minecraft 1.13
- Plugin version: 2.0.0-rc4-legacy (Premium)
- No other plugins installed
- Default config, default menu

When menu item (e.g compass) is used on any block, items inside gui do not register beeing clicked and get duplicated if the player has appropriate permission. When clicking in the air, everything works as intended

**Comment by Derkades** [comment]
Thanks for reporting this bug. Can you try the beta? You can download it in the #beta channel on discord or compile it from the master branch here.

**Comment by Kalendarz2** [comment]
I don't have appropriate rank to view this channel. How can I verify my premium?

**Comment by Derkades** [comment]
You can verify your account by [sending a message on spigot](https://www.spigotmc.org/conversations/add?to=RobinMC) with your Discord username (from the account used to purchase the resource).
