### ISSUE TITLE
Unable to use certain actions [NPE]

### ISSUE THREAD

**Issue by FendiTony777** [ServerSelectorX/ServerSelectorX#151]
Im unable to use certain actions such as
action: 'none'
action: 'close'
action: 'sel:menu2'

I really need help i think this is not an error of mine. The same default config works fine , but if i put 'none' as an action anywhere it breaks the plugin.

Using Premium-rc4

my configs:

default.yml > [default](https://paste.gg/p/thevipershow/be2308102179486ebf8849211119aa0b)

vanillaop.yml > [vanillaop](https://paste.gg/p/thevipershow/b442303e7d394781babe9610b60eb34f)

**Comment by Derkades** [comment]
The item format is different when the action is not set to `srv`: https://github.com/ServerSelectorX/ServerSelectorX/wiki/Menu-items-premium
