### ISSUE TITLE
Players can swap items into offhand even with cancel-item-move:true

### ISSUE THREAD

**Issue by jakkuh** [ServerSelectorX/ServerSelectorX#155]
Even with `cancel-item-move: true` players can still put the item into their off hand.

When they relog they then have multiple compasses.

Paper Build 1618 (Minecraft 1.12.2)

**Comment by Derkades** [comment]
Currently only the non-legacy versions support offhands, I should fix this

**Comment by Derkades** [comment]
This has been fixed in version 3.5.2
