### ISSUE TITLE
Clear Inventory Option

### ISSUE THREAD

**Issue by jakkuh** [ServerSelectorX/ServerSelectorX#156]
Would be good to have an option to clear player inventories when they log on, for use in hub servers.

**Comment by Derkades** [comment]
This feature is present in the premium version

**Comment by jakkuh** [comment]
I purchased the premium version, but I don't want to use the ServerConnector. Is there an option to use it without it? I just use PlaceholderAPI to grab server info (like player count, etc).

**Comment by Derkades** [comment]
You don't need to use SSX-Connector, if you don't want to use it, don't install it. The menu will still open.
