### ISSUE TITLE
World whitelist for effects on join

### ISSUE THREAD

**Issue by Derkades** [ServerSelectorX/ServerSelectorX#161]
or maybe even custom join actions

**Comment by McHauge** [comment]
This would open up the use of a more shared config to be synced between servers without all servers utilizing all options at once

A "server" whitelist might also be an option that could be useful when working with bungeecord
-effect
-item (mainly the "give" portion)
-inventory (for individual options or as a group, item drop/clear and so on)
-commands config (limit certain commands to some servers only)

**Comment by Derkades** [comment]
I will not add server whitelist options. You can already choose which servers you want to enable specific features on by just disabling the options. If you use config sync and the file differs per server, you can choose not to sync that file.

I don't think adding a server whitelist to disable an item in a certain server is more convenient than just not syncing that file.
