### ISSUE TITLE
Actions don't work.

### ISSUE THREAD

**Issue by MCUniversity** [ServerSelectorX/ServerSelectorX#174]
Actions don't work. The items exist and the menu opens but nothing happens.
This is a 1.8.9 server connected to bungeecord.

Config:
https://hasteb.in/igagequr.yml
Config 2:
https://hasteb.in/nemorabo.yml

**Comment by Derkades** [comment]
Have you tried other actions like the message action?

**Comment by MCUniversity** [comment]
I tried the command action and the close one. Also did not work.

**Comment by MCUniversity** [comment]
I only tried the command, srv and close actions.

**Comment by MCUniversity** [comment]
More info: 
When I open the menu and press on any of the items that have an action, they just get placed back into their place in the gui and nothing happens. No error pops up in the console.

Plugins list:
Citizens
CoreProtect
EssentialsX
EssentialsXspawn
EssentialsXchat
FAWE
Holographic displays
JoinMaster
NightVision
PermissionsEx
Placeholder API
Protocol Lib
Server selector X
Vault
ViaRewind
ViaVersion
WorldEdit
WorldGuard

**Comment by Derkades** [comment]
resolved in discord by fixing indentation and moving the action option back to its original place
