### ISSUE TITLE
Plugin not properly shutting down async tasks

### ISSUE THREAD

**Issue by ShayPunter** [ServerSelectorX/ServerSelectorX#175]
Hello,

I am currently in the process of setting up a new network server, upon shutting down the hub server, this message appears in the console:
![image](https://user-images.githubusercontent.com/18310437/82742064-1a74de80-9d51-11ea-884e-c7aa5563f170.png)

"Nag author [you] about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before the process dies."

I am using the latest version of [Tuinity](https://github.com/Spottedleaf/Tuinity)

**Comment by Derkades** [comment]
Which ServerSelectorX version are you using? `/version ServerSelectorX`

**Comment by ShayPunter** [comment]
That would be v3.6.0, sorry forgot to add that in the message!

**Comment by Derkades** [comment]
I've rewritten server pinging completely, again. This is gone now
