### ISSUE TITLE
Random Error

### ISSUE THREAD

**Issue by Jakaboii** [ServerSelectorX/ServerSelectorX#187]
I'm using the premium version, and whenever I open the server selector it sends this error to the console, even though the server selector works fine

Each time it may send a different task number too

https://hatebin.com/nbylosihpu

**Comment by Derkades** [comment]
Did you set an item material to `AIR`?

**Comment by Jakaboii** [comment]
oh, yes I did

Removing it worked, thanks

**Comment by Derkades** [comment]
If you want to always hide the item remove it. If you want to hide the item only for a specific section, set the material to `NONE`
