### ISSUE TITLE
FileUtils missing

### ISSUE THREAD

**Issue by Lmmb74** [ServerSelectorX/ServerSelectorX#215]
Hello. While using spigot 1.16.4 (latest build at the time of submitting this issue), the plugin doesn't enable (I've built the master branch) and throws `java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils`. I've tried both using Java 11 and Java 8, which I know was a long shot, but I hope this info gives more insight. Thanks in advance for any help.

**Comment by Derkades** [comment]
Did you compile it yourself or the builds from https://ci.derkad.es?

**Comment by Lmmb74** [comment]
I compiled it myself

**Comment by Lmmb74** [comment]
Welp, I downloaded the one from the build server and it worked, so I'm closing this and thanks :D

**Comment by Derkades** [comment]
If you want to build it yourself make sure to trigger the shade plugin `mvn package shade:shade`

**Comment by Lmmb74** [comment]
Ok, thanks :D

**Comment by Lmmb74** [comment]
Also thanks for adding the motd change feature, since I was the one who submitted the feature request. 3 years later, but better late than never xD
