### ISSUE TITLE
Placeholder Update - Pinger

### ISSUE THREAD

**Issue by Lmmb74** [ServerSelectorX/ServerSelectorX#216]
Hello. I've set pinger refresh rate to 1 second. And the menu updates just fine when a player leaves the server. (While looking at the menu, it goes down form 1 to 0 just fine). But the menu doesn't seem to update when a player connects to such server. (The placeholder stays on 0). Any ideas?

**Comment by Derkades** [comment]
Is this the {online} placeholder? How many servers do you use SSX on? Is interval set to 1 second in the connector config file and is the menu refresh interval set to 20 ticks as well?

**Comment by Lmmb74** [comment]
The placeholder I was using is a PAPI one (%pinger_players_<server_ip>:<port>%). I'm not using the connector for that. But I'll check the refresh interval of the menu. Thanks for the info.

**Comment by Lmmb74** [comment]
Despite setting update-interval to 20 in the menu config, the issue still occurs.

**Comment by Lmmb74** [comment]
It also happens with the `{online}` placeholder. It doesn't update when a player joins the server, but it does when a player leaves.

**Comment by Lmmb74** [comment]
Any idea?
