### ISSUE TITLE
TP with WE

### ISSUE THREAD

**Issue by l4zs** [ServerSelectorX/ServerSelectorX#219]
if you rightclick with it and have WorldEdit installed, it tps you to the block you're looking at.

To fix this you should just do event.setCancelled(true);
in the InteractEvent Class right before you open the inventory ^^

**Comment by Derkades** [comment]
You can disable the worledit navigation wand in the worldedit configuration file. The premium version has an option to enable event.setCancelled(true) but this is mainly indented for items with a vanilla use like fishing rods or hoes.
