### ISSUE TITLE
My guy.... xD

### ISSUE THREAD

**Issue by BlueSky-fur** [ServerSelectorX/ServerSelectorX#264]
I want to point out that we can get the ServerSelectorX Premium version free from your jenkins btw 
https://ci.derkad.es/view/ServerSelectorX/job/ServerSelectorX%20Premium/334/artifact/target/

**Comment by Derkades** [comment]
Yep, this is intentional, it is linked in the readme as well. The plugin is GPL-licensed and you can use it for free, just don't expect support.

**Comment by BlueSky-fur** [comment]
Cheers, was worried for a second since ive had a situation like this before but the guy didnt want to share it for free thanks for the quick answer!

**Comment by MrEisbear** [comment]
You are a absolutly wonderful person for that
