### ISSUE TITLE
The new update breaks action

### ISSUE THREAD

**Issue by WongIong** [ServerSelectorX/ServerSelectorX#310]
![image](https://user-images.githubusercontent.com/36799194/173209117-ca1ec2a0-bb3b-47eb-8973-10002f5a6d87.png)

**Comment by Derkades** [comment]
Thanks for the report, it should now be fixed. You can get a beta jar here: https://ci.rkslot.nl/view/ServerSelectorX/

**Comment by WongIong** [comment]
Thanks :)
