### ISSUE TITLE
ServerSelectorX Plugin Throws NoClassDefFoundError on Player Join and Interact Events

### ISSUE THREAD

**Issue by var1nthon** [ServerSelectorX/ServerSelectorX#395]
**Describe the bug**
When a player joins the server or interacts with certain items, the ServerSelectorX plugin throws a NoClassDefFoundError related to NBTReflectionUtil. This error prevents certain functionalities of the plugin from working as expected.

**To Reproduce**
1. Start the Minecraft server with the ServerSelectorX plugin enabled.
2. Have a player join the server.
3. Observe the console for the NoClassDefFoundError.
4. Attempt to interact with items that trigger the ServerSelectorX plugin.
5. Observe the console for further errors.

**Expected behavior**
The ServerSelectorX plugin should function correctly without throwing errors, allowing players to join the server and interact with items as expected.

**Proxy environment**
- Using Velocity proxy
- Server running in offline/insecure mode

**Minecraft versions used**
- Minecraft version 1.21.1
- Paper version 1.21.1-40

**Relevant plugins**
- ServerSelectorX vPremium-3.1.4
- PlaceholderAPI v2.11.6
- ProtocolLib v5.3.0-SNAPSHOT-726
- CMI v9.7.5.3
- LuckPerms v5.4.139

**Log**
Latest.log: https://paste.denizenscript.com/View/125890

**Comment by var1nthon** [comment]
When I updated to SSX 3.1.5 this problem went away.

**Comment by Derkades** [comment]
Yes, I should make a new release to spigot soon as the current "stable" version does not work with latest Minecraft
