### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by NemanjaMAX** [ServerSelectorX/ServerSelectorX#79]
https://www.spigotmc.org/threads/serverselectorx-error-weird-xd.302728/

**Comment by Derkades** [comment]
Make sure the titles of your menus are different and that you use a different item and command (or no item/command at all)

A few other things I have noticed in your config:
- `action: 'server:survival'` should be `action: 'srv:survival'`
- `ip: 0.0.0.0:25568` - `0.0.0.0` is not a valid IP, and remove the port from the ip
- You have no indentation/spaces in your config. Is this a problem with copy pasting to spigotmc.org or with your config?

**Comment by NobodyPAWN** [comment]
Close it freely, btw i'm NemanjaMAX :)
